### ISSUE TITLE
Stuck at 99.17%

### ISSUE THREAD

**Issue by vaibhavsanwa** [AggressiveUser/AllForOne#5]

**Comment by vaibhavsanwa** [comment]
![image](https://github.com/AggressiveUser/AllForOne/assets/58941903/af9a5130-42c2-4c30-99f7-fb40849c327e)

**Comment by mojtaba13133** [comment]
> ![image](https://user-images.githubusercontent.com/58941903/245405812-af9a5130-42c2-4c30-99f7-fb40849c327e.png)

On any number, if it stops, that repository has probably been deleted. You can delete that line using the corresponding line number and run the command again.
For example, in your image, the repository is line 120 of the file
https://github.com/AggressiveUser/AllForOne/blob/main/PleaseUpdateMe.txt
It is not available. Removing line 120 solves the problem
